version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - "3307:3306"  # <- Externa:Interna
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: